import "server-only";

export {
  activateLicense,
  changeLicenseTerms,
  createLicense,
  createLicenseService,
  getLicense,
  getProvisioningEligibility,
  listLicenseAuditEvents,
  listLicenseTermsVersions,
  listLicenses,
  renewLicense,
  suspendLicense,
  terminateLicense,
  type LicenseService,
  type LicenseServiceDependencies,
} from "./license.service";
export {
  LicenseServiceError,
  type LicenseServiceErrorCode,
} from "./license.errors";
export {
  LICENSE_PLAN_CATALOG,
  type ChangeLicenseTermsInput,
  type CreateLicenseInput,
  type License,
  type LicenseAuditCursor,
  type LicenseAuditEvent,
  type LicenseAuditEventType,
  type LicenseAuditPage,
  type LicenseDetail,
  type LicenseEligibility,
  type LicenseEligibilityReason,
  type LicenseLifecycleInput,
  type LicenseListItem,
  type LicenseListPage,
  type LicensePlanKey,
  type LicenseProvisioningEligibilityInput,
  type LicenseProvisioningEligibilityResult,
  type LicenseStatus,
  type LicenseTermsPage,
  type LicenseTermsVersion,
  type LicenseValidity,
  type ListLicenseAuditEventsInput,
  type ListLicenseTermsVersionsInput,
  type ListLicensesInput,
  type RenewLicenseInput,
} from "./license.types";
